Repository htl-grieskirchen-core/core, pull requests merged in 2022-12, with the labels that each got.

#153 nginx and docker setup
  .dockerignore
  CODEOWNERS
  Core.AuthLib/AuthConfigurator.cs
  Core.Backend.Secure/Core.Backend.Secure.csproj
  Core.Backend.Secure/Program.cs
  Core.Backend.Secure/appsettings.json
  Core.Backend/Core.Backend.csproj
  Core.Backend/Program.cs
  Dockerfile
  deployment/backend.Dockerfile
  deployment/backend.secure.Dockerfile
  deployment/docker-compose.yml
  deployment/nginx/mainframe-config.json
  deployment/nginx/nginx.Dockerfile
  deployment/nginx/nginx.conf
  deployment/plugins/backend/.gitkeep
  deployment/plugins/web/.gitkeep
  deployment/private-keys/.gitignore
  deployment/public-keys/.gitignore
  docker-compose.yml
  frontend/.dockerignore
  mainframe/index.html
  mainframe/mainframe-config.json
Labels: enhancement, Docker goes brrrr

#164 add user info endpoint
  Core.Backend.Secure/Controllers/PwController.cs
  Core.Backend.Secure/Controllers/UserController.cs
  Core.Backend.Secure/Dtos/UserDTO.cs
  Core.Backend.Secure/Program.cs
  Core.Backend.Secure/Services/UserService.cs
Labels: backend

#170 Feature/update mainframe
  CODEOWNERS
  Core.Backend.Secure/Auth/IDToken.cs
  Core.Backend.Secure/Controllers/AuthController.cs
  Core.Backend.Secure/Controllers/PwController.cs
  Core.Backend.Secure/Program.cs
  Core.Backend.Secure/Services/AuthService.cs
  Core.Backend.Secure/Services/CredService.cs
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/libs/mainframe-connector/src/lib/mainframe-id-token.service.ts
  mainframe/index.html
Labels: backend

#177 trim pwd creds
  mainframe/index.html
Labels: enhancement

#167 Feature/home component
  frontend/apps/frontend/src/app/app-routing.module.ts
  frontend/apps/frontend/src/app/app.module.ts
  frontend/apps/frontend/src/app/home/category/category.component.css
  frontend/apps/frontend/src/app/home/category/category.component.html
  frontend/apps/frontend/src/app/home/category/category.component.spec.ts
  frontend/apps/frontend/src/app/home/category/category.component.ts
  frontend/apps/frontend/src/app/home/home.module.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/plugin/plugin.component.html
  frontend/apps/frontend/src/app/home/plugin/plugin.component.scss
  frontend/apps/frontend/src/app/home/plugin/plugin.component.spec.ts
  frontend/apps/frontend/src/app/home/plugin/plugin.component.ts
  frontend/apps/frontend/src/assets/icons/border-all.svg
  frontend/apps/frontend/src/assets/icons/hourglass-low.svg
  frontend/apps/frontend/src/assets/icons/star.svg
  frontend/apps/frontend/src/assets/icons/user-search.svg
  frontend/libs/mainframe-connector/src/index.ts
  frontend/libs/mainframe-connector/src/lib/mainframe-connector.module.ts
  mainframe/index.html
Labels: dua moi wos, legendary git action

#192 fix ci annotations
  Core.Backend.Secure/Auth/IDToken.cs
  Core.Backend.Secure/Controllers/AuthController.cs
  Core.Backend.Secure/Dtos/UserDTO.cs
Labels: enhancement, fix

#188 Feature/list view
  frontend/apps/frontend/src/app/app-routing.module.ts
  frontend/apps/frontend/src/app/home/category/category.component.ts
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.css
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.html
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.spec.ts
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
  frontend/apps/frontend/src/app/home/home.module.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.css
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.html
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.spec.ts
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.ts
  frontend/apps/frontend/src/app/home/list-view/list-view.component.css
  frontend/apps/frontend/src/app/home/list-view/list-view.component.html
  frontend/apps/frontend/src/app/home/list-view/list-view.component.spec.ts
  frontend/apps/frontend/src/app/home/list-view/list-view.component.ts
  frontend/apps/frontend/src/app/home/plugin/plugin.component.html
  mainframe/index.html
Labels: setz-moi-tags, add-moi-a-issue
