Repository htl-grieskirchen-core/core, pull requests merged in 2023-03, with the labels that each got.

#289 Tests/webuntis
  .github/workflows/backend.yml
  Core.WebUntis.Implementation/WebUntisClient.cs
  Core.WebUntis.Interface/Exceptions/BadCredentialsException.cs
  Core.WebUntis.Tests/Core.WebUntis.Tests.csproj
  Core.WebUntis.Tests/UnitTest1.cs
  Core.WebUntis.Tests/Usings.cs
  Core.sln
Labels: backend

#298 Deploy moi
  .DS_Store
  .github/workflows/backend.yml
  Core.WebUntis.Implementation/WebUntisClient.cs
  Core.WebUntis.Interface/Exceptions/BadCredentialsException.cs
  Core.WebUntis.Tests/Core.WebUntis.Tests.csproj
  Core.WebUntis.Tests/UnitTest1.cs
  Core.WebUntis.Tests/Usings.cs
  Core.sln
  frontend/apps/auth/src/app/login/login.component.html
  frontend/apps/auth/src/app/onboarding.service.ts
  frontend/apps/auth/src/app/onboarding/onboarding.component.html
  frontend/apps/auth/src/app/onboarding/onboarding.component.ts
  frontend/apps/auth/src/app/onboarding/onboarding.module.ts
  frontend/apps/frontend/src/app/app.component.html
  frontend/apps/frontend/src/app/app.component.ts
  frontend/apps/frontend/src/app/core/nav-bar.service.ts
  frontend/apps/frontend/src/app/core/search.service.ts
  frontend/apps/frontend/src/app/home/category/category.component.html
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.html
  frontend/apps/frontend/src/app/home/home.module.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/plugin/plugin.component.ts
  frontend/apps/frontend/src/app/icons/icons.module.ts
  frontend/apps/frontend/src/app/shared/footer/footer.component.css
  frontend/apps/frontend/src/app/shared/footer/footer.component.html
  frontend/apps/frontend/src/app/shared/footer/footer.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.ts
  frontend/apps/frontend/src/app/shared/search-bar/search-bar.component.css
  frontend/apps/frontend/src/app/shared/search-bar/search-bar.component.html
  frontend/apps/frontend/src/app/shared/search-bar/search-bar.component.spec.ts
  frontend/apps/frontend/src/app/shared/search-bar/search-bar.component.ts
  frontend/apps/frontend/src/app/shared/search/search.component.css
  frontend/apps/frontend/src/app/shared/search/search.component.html
  frontend/apps/frontend/src/app/shared/search/search.component.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/apps/frontend/src/app/shared/syno-btn/syno-btn.component.css
  frontend/apps/frontend/src/app/shared/syno-btn/syno-btn.component.html
  frontend/apps/frontend/src/app/shared/syno-btn/syno-btn.component.ts
  frontend/apps/frontend/src/app/shared/syno-nav-tab/syno-nav-tab.component.css
  frontend/apps/frontend/src/app/shared/syno-nav-tab/syno-nav-tab.component.html
  frontend/apps/frontend/src/app/shared/syno-nav-tab/syno-nav-tab.component.ts
  frontend/apps/frontend/src/assets/bg-line.svg
  frontend/tailwind.config.js
Labels: deployment

#321 Deployment
  frontend/apps/auth/src/app/login/login.component.ts
  frontend/apps/auth/src/app/mainframe.service.ts
  frontend/apps/auth/src/app/onboarding.service.ts
  frontend/apps/auth/src/app/onboarding/onboarding.component.ts
  frontend/apps/frontend/src/app/app-routing.module.ts
  frontend/apps/frontend/src/app/app.module.ts
  frontend/apps/frontend/src/app/core/nav-bar.service.ts
  frontend/apps/frontend/src/app/core/search.service.ts
  frontend/apps/frontend/src/app/home/category/category.component.html
  frontend/apps/frontend/src/app/home/category/category.component.ts
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.html
  frontend/apps/frontend/src/app/home/home.module.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/list-view/list-view.component.html
  frontend/apps/frontend/src/app/home/plugin/plugin.component.ts
  frontend/apps/frontend/src/app/icons/icons.module.ts
  frontend/apps/frontend/src/app/plugin/plugin.component.html
  frontend/apps/frontend/src/app/plugin/plugin.component.ts
  frontend/apps/frontend/src/app/settings/settings-routing.module.ts
  frontend/apps/frontend/src/app/settings/settings.component.css
  frontend/apps/frontend/src/app/settings/settings.component.html
  frontend/apps/frontend/src/app/settings/settings.component.spec.ts
  frontend/apps/frontend/src/app/settings/settings.component.ts
  frontend/apps/frontend/src/app/settings/settings.module.ts
  frontend/apps/frontend/src/app/shared/grid-plugin/grid-plugin.component.css
  frontend/apps/frontend/src/app/shared/grid-plugin/grid-plugin.component.html
  frontend/apps/frontend/src/app/shared/grid-plugin/grid-plugin.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/search/search.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/search/search.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.html
  frontend/apps/frontend/src/app/shared/search-result/search-result.component.css
  frontend/apps/frontend/src/app/shared/search-result/search-result.component.html
  frontend/apps/frontend/src/app/shared/search-result/search-result.component.ts
  frontend/apps/frontend/src/app/shared/search/search.component.css
  frontend/apps/frontend/src/app/shared/search/search.component.html
  frontend/apps/frontend/src/app/shared/search/search.component.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/apps/mainframe/src/app/handler.ts
  frontend/apps/mainframe/src/app/login.ts
  frontend/apps/mainframe/src/app/main.ts
  frontend/apps/mainframe/src/handler/getPluginList.ts
  frontend/apps/mainframe/src/handler/login.ts
  frontend/apps/mainframe/src/handler/saveToken.ts
  frontend/apps/mainframe/src/handler/sendRequest.ts
  frontend/apps/mainframe/src/types/handler.guards.ts
  frontend/apps/mainframe/src/types/handler.ts
  frontend/apps/mainframe/src/utils/fetch.ts
  frontend/package.json
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: deployment

#323 fix GetRole
  Core.AuthLib/AuthExtensions.cs
Labels: bug

#324 Quickfix
  Core.AuthLib/AuthExtensions.cs
  Core.AuthLib/Services/RsaService.cs
Labels: bug

#278 Feature/user favorites
  Core.Backend.Secure/Controllers/UserController.cs
  Core.Backend.Secure/Core.Backend.Secure.csproj
  Core.Backend.Secure/Program.cs
  Core.Backend.Secure/Services/AuthService.cs
  Core.Backend.Secure/Services/CSVReaderService.cs
  Core.Backend.Secure/Services/CredService.cs
  Core.Backend.Secure/Services/UserService.cs
  Core.Backend.Secure/Services/WebUntisService.cs
  Core.Backend/Controllers/UserController.cs
  Core.Backend/Core.Backend.csproj
  Core.Backend/Dtos/UserFavoriteDto.cs
  Core.Backend/Program.cs
  Core.Backend/Services/DatabaseBackgroundService.cs
  Core.Backend/Services/UserFavoritesService.cs
  Core.Backend/appsettings.json
  Core.Database/Core.Database.csproj
  Core.Database/CoreContext.cs
  Core.Database/UserFavorite.cs
  Core.Secure.Database/Core.Secure.Database.csproj
  Core.Secure.Database/CoreSecureContext.cs
  Core.Secure.Database/StoredUserTokens.cs
  Core.Secure.Database/Student.cs
  Core.Secure.Database/Teacher.cs
  Core.Secure.Database/User.cs
  Core.sln
Labels: backend, dua moi wos, legendary git action, eigentlich-katastrophe

#335 Fix error handling in login and onboarding process
  frontend/apps/auth/src/app/login/login.component.ts
  frontend/apps/auth/src/app/mainframe.service.ts
  frontend/apps/auth/src/app/onboarding.service.ts
  frontend/apps/auth/src/app/onboarding/onboarding.component.ts
  frontend/apps/mainframe/src/handler/login.ts
Labels: frontend, fix, eigentlich-katastrophe

#334 Update Settings
  frontend/apps/frontend/src/app/core/nav-bar.service.ts
  frontend/apps/frontend/src/app/settings/settings.component.html
  frontend/apps/frontend/src/app/settings/settings.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/mainframe/src/app/handler.ts
  frontend/apps/mainframe/src/handler/getPublicKey.ts
Labels: frontend

#339 Merge ma heid wieda wos?
  frontend/apps/auth/src/app/login/login.component.ts
  frontend/apps/auth/src/app/mainframe.service.ts
  frontend/apps/auth/src/app/onboarding.service.ts
  frontend/apps/auth/src/app/onboarding/onboarding.component.ts
  frontend/apps/frontend/src/app/core/nav-bar.service.ts
  frontend/apps/frontend/src/app/home/category/category.component.html
  frontend/apps/frontend/src/app/settings/settings.component.html
  frontend/apps/frontend/src/app/settings/settings.component.ts
  frontend/apps/frontend/src/app/shared/footer/footer.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/frontend/src/app/shared/search/search.component.html
  frontend/apps/frontend/src/app/shared/search/search.component.ts
  frontend/apps/mainframe/src/app/handler.ts
  frontend/apps/mainframe/src/handler/getPublicKey.ts
  frontend/apps/mainframe/src/handler/login.ts
  frontend/libs/core-ui/src/lib/syno-select-multiple/syno-select-multiple.component.html
  frontend/package.json
  frontend/yarn.lock
Labels: deployment
