Repository htl-grieskirchen-core/core, pull requests merged in 2023-01, with the labels that each got.

#187 Provide list of plugins to frontend
  frontend/apps/frontend/src/app/home/category/category.component.ts
  frontend/apps/frontend/src/app/home/dashboard/dashboard.component.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.ts
  frontend/apps/frontend/src/app/home/list-view/list-view.component.ts
  frontend/libs/mainframe-connector/src/index.ts
  frontend/libs/mainframe-connector/src/lib/plugin-list.service.spec.ts
  frontend/libs/mainframe-connector/src/lib/plugin-list.service.ts
  frontend/libs/mainframe-connector/src/lib/plugin.ts
  mainframe/index.html
  mainframe/mainframe-config.json
Labels: enhancement, dua moi wos

#214 Feature/nav bar
  README.md
  frontend/apps/frontend/src/app/app.component.html
  frontend/apps/frontend/src/app/app.component.ts
  frontend/apps/frontend/src/app/app.module.ts
  frontend/apps/frontend/src/app/icons/icons.module.ts
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.spec.ts
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.spec.ts
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/package.json
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: setz-moi-assignees

#209 Feature/tag components
  frontend/apps/frontend/src/app/home/home.module.ts
  frontend/apps/frontend/src/app/home/home/home.component.html
  frontend/apps/frontend/src/app/home/home/home.component.ts
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.html
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.ts
  frontend/apps/frontend/src/app/home/list-view/list-view.component.ts
  frontend/apps/frontend/src/app/home/plugin/plugin.component.html
  frontend/apps/frontend/src/app/home/plugin/plugin.component.ts
  frontend/apps/frontend/src/app/shared/classes/tagColors.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/apps/frontend/src/app/shared/tag/tag.component.css
  frontend/apps/frontend/src/app/shared/tag/tag.component.html
  frontend/apps/frontend/src/app/shared/tag/tag.component.spec.ts
  frontend/apps/frontend/src/app/shared/tag/tag.component.ts
Labels: setz-moi-assignees

#212 Feature/integrate plugin quote of today
  Core.Backend/Pluginloader.cs
  Core.Backend/Program.cs
  frontend/apps/auth/src/app/login/daily-quote/daily-quote.component.html
  frontend/apps/auth/src/app/login/daily-quote/daily-quote.component.ts
  frontend/apps/auth/src/app/login/login.module.ts
  frontend/apps/auth/src/environments/environment.prod.ts
  frontend/apps/auth/src/environments/environment.ts
  frontend/apps/frontend/src/app/home/list-view-item/list-view-item.component.html
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement, frontend, backend

#183 Create InputField components
  frontend/apps/frontend/src/app/app.module.ts
  frontend/apps/frontend/src/app/shared/email-input/email-input.component.css
  frontend/apps/frontend/src/app/shared/email-input/email-input.component.html
  frontend/apps/frontend/src/app/shared/email-input/email-input.component.ts
  frontend/apps/frontend/src/app/shared/password-input/password-input.component.css
  frontend/apps/frontend/src/app/shared/password-input/password-input.component.html
  frontend/apps/frontend/src/app/shared/password-input/password-input.component.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/apps/frontend/src/app/shared/username-input/username-input.component.html
  frontend/apps/frontend/src/app/shared/username-input/username-input.component.ts
Labels: setz-moi-tags

#193 Implement WebUntis API
  Core.Backend.Secure/CSV/.gitignore
  Core.Backend.Secure/Controllers/PwController.cs
  Core.Backend.Secure/Controllers/WebUntisController.cs
  Core.Backend.Secure/Core.Backend.Secure.csproj
  Core.Backend.Secure/Dtos/TeacherDTO.cs
  Core.Backend.Secure/Program.cs
  Core.Backend.Secure/Services/AuthService.cs
  Core.Backend.Secure/Services/CSVReaderService.cs
  Core.Backend.Secure/Services/CredService.cs
  Core.Backend.Secure/Services/WebUntisService.cs
  Core.Backend.Secure/appsettings.json
  Core.Backend/Controllers/WeatherForecastController.cs
  Core.Backend/Core.Backend.csproj
  Core.Backend/WeatherForecast.cs
  Core.Database/CoreContext.cs
  Core.Database/StoredUserTokens.cs
  Core.Database/Student.cs
  Core.Database/Teacher.cs
  Core.WebUntis.Implementation/Core.WebUntis.Implementation.csproj
  Core.WebUntis.Implementation/RequestTypes/AuthenticateRequest.cs
  Core.WebUntis.Implementation/RequestTypes/AuthenticateWithSecretRequest.cs
  Core.WebUntis.Implementation/RequestTypes/ExamRequest.cs
  Core.WebUntis.Implementation/RequestTypes/TimetableRequest.cs
  Core.WebUntis.Implementation/ResponseTypes/AuthenticateResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/ClassResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/ExamTypeResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/HolidayResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/HomeworkResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/RoomResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/SubjectResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/TimetableResponse.cs
  Core.WebUntis.Implementation/UntisDateTimeMethods.cs
  Core.WebUntis.Implementation/WebUntisClient.cs
  Core.WebUntis.Interface/Exceptions/InsufficientRightsException.cs
  Core.WebUntis.Interface/Exceptions/InvalidDateException.cs
  Core.WebUntis.Interface/Exceptions/InvalidTokenException.cs
  Core.WebUntis.Interface/Exceptions/WebUntisException.cs
  Core.WebUntis.Interface/IWebUntisClient.cs
  Core.WebUntis.Interface/Types/Authentication.cs
  Core.WebUntis.Interface/Types/Class.cs
  Core.WebUntis.Interface/Types/Code.cs
  Core.WebUntis.Interface/Types/ElementType.cs
  Core.WebUntis.Interface/Types/Holiday.cs
  Core.WebUntis.Interface/Types/Homework.cs
  Core.WebUntis.Interface/Types/LessonType.cs
  Core.WebUntis.Interface/Types/PersonType.cs
  Core.WebUntis.Interface/Types/Room.cs
  Core.WebUntis.Interface/Types/Student.cs
  Core.WebUntis.Interface/Types/Subject.cs
  Core.WebUntis.Interface/Types/Timetable.cs
Labels: backend, dua moi wos, legendary git action, eigentlich-katastrophe

#250 HTTPS-Deployment
  .github/workflows/deployment.yml
  deployment/.env.example
  deployment/caddy-data/.gitignore
  deployment/caddy/Caddyfile
  deployment/caddy/caddy.Dockerfile
  deployment/caddy/entrypoint.sh
  deployment/caddy/mainframe-config.json
  deployment/docker-compose.yml
  deployment/nginx/entrypoint.sh
  deployment/nginx/nginx.Dockerfile
  deployment/nginx/nginx.conf
Labels: enhancement, backend

#252 Feature/auto deploy update builder dings hüfe
  .github/workflows/deployment.yml
  deployment/builder.sh
  deployment/caddy/mainframe-config.json
  frontend/apps/frontend/src/app/home/home/home.component.html
  mainframe/index.html
  mainframe/mainframe-config.json
Labels: backend, plugin, Docker goes brrrr, dua moi nix, eigentlich-katastrophe

#230 Feature/nav bar
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/nav-bar.component.ts
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.css
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.html
  frontend/apps/frontend/src/app/shared/nav-bar/tab/tab.component.ts
Labels: good first issue, setz-moi-tags, add-moi-a-issue, setz-moi-assignees, setz-moi-project

#255 Class Timetable
  Core.Backend.Secure/Controllers/WebUntisController.cs
  Core.Backend.Secure/Services/WebUntisService.cs
  Core.WebUntis.Implementation/WebUntisClient.cs
  Core.WebUntis.Interface/IWebUntisClient.cs
Labels: backend

#257 add TeacherTimetable Endpoint
  Core.Backend.Secure/Controllers/WebUntisController.cs
  Core.Backend.Secure/Services/WebUntisService.cs
  Core.WebUntis.Implementation/RequestTypes/TimetableRequest.cs
  Core.WebUntis.Implementation/ResponseTypes/HomeworkResponse.cs
  Core.WebUntis.Implementation/ResponseTypes/TimetableResponse.cs
  Core.WebUntis.Implementation/WebUntisClient.cs
Labels: backend

#260 feature/core-UI-library
  frontend/apps/frontend/src/app/app.module.ts
  frontend/apps/frontend/src/app/shared/shared.module.ts
  frontend/libs/core-ui/src/lib/core-ui.module.ts
  frontend/libs/core-ui/src/lib/syno-base/syno-base.component.ts
  frontend/libs/core-ui/src/lib/syno-button/syno-button.component.ts
  frontend/libs/core-ui/src/lib/syno-email/syno-email.component.css
  frontend/libs/core-ui/src/lib/syno-email/syno-email.component.html
  frontend/libs/core-ui/src/lib/syno-email/syno-email.component.ts
  frontend/libs/core-ui/src/lib/syno-password/syno-password.component.css
  frontend/libs/core-ui/src/lib/syno-password/syno-password.component.html
  frontend/libs/core-ui/src/lib/syno-password/syno-password.component.ts
  frontend/libs/core-ui/src/lib/syno-username/syno-username.component.html
  frontend/libs/core-ui/src/lib/syno-username/syno-username.component.ts
Labels: frontend
